"""PR-13A fixed replay generated by the real host-side BaB driver."""

# pylint: disable=duplicate-code

import torch

from boundflow.ir.task import BFTaskModule, BoundTask, TaskKind, TaskOp
from boundflow.runtime.bab import BabConfig, solve_bab_mlp
from boundflow.runtime.bab_query import (
    BoundQueryRequest,
    FixedBabQueryRecorder,
    build_query_batch,
    compare_query_results,
    execute_query_batch_reference,
    replay_fixed_query_trace,
)
from boundflow.runtime.query_executor import execute_alpha_beta_query_batch
from boundflow.runtime.task_executor import InputSpec


def _make_two_relu_module() -> BFTaskModule:
    task = BoundTask(
        task_id="t0",
        kind=TaskKind.INTERVAL_IBP,
        ops=[
            TaskOp(
                op_type="linear",
                name="linear1",
                inputs=["input", "W1", "b1"],
                outputs=["h1"],
            ),
            TaskOp(op_type="relu", name="relu1", inputs=["h1"], outputs=["r1"]),
            TaskOp(
                op_type="linear",
                name="linear2",
                inputs=["r1", "W2", "b2"],
                outputs=["h2"],
            ),
            TaskOp(op_type="relu", name="relu2", inputs=["h2"], outputs=["r2"]),
            TaskOp(
                op_type="linear",
                name="linear3",
                inputs=["r2", "W3", "b3"],
                outputs=["out"],
            ),
        ],
        input_values=["input"],
        output_values=["out"],
    )
    params = {
        "W1": torch.tensor([[1.0], [-1.0]], dtype=torch.float32),
        "b1": torch.tensor([0.1, -0.1], dtype=torch.float32),
        "W2": torch.tensor([[1.0, -0.5], [-0.25, 1.0]], dtype=torch.float32),
        "b2": torch.tensor([-0.2, 0.15], dtype=torch.float32),
        "W3": torch.tensor([[1.0, -0.75]], dtype=torch.float32),
        "b3": torch.tensor([-0.1], dtype=torch.float32),
    }
    return BFTaskModule(tasks=[task], entry_task_id="t0", bindings={"params": params})


def test_pr13a_real_bab_stream_replays_without_query_loss() -> (
    None
):  # pylint: disable=too-many-locals
    """Record a multi-node search and reproduce every oracle result in order."""

    torch.manual_seed(0)
    module = _make_two_relu_module()
    spec = InputSpec.linf(
        value_name="input",
        center=torch.tensor([[0.0]], dtype=torch.float32),
        eps=1.0,
    )
    recorder = FixedBabQueryRecorder()
    config = BabConfig(
        max_nodes=9,
        oracle="alpha_beta",
        node_batch_size=1,
        enable_node_eval_cache=False,
        alpha_steps=0,
        alpha_init=0.5,
        beta_init=0.0,
        threshold=0.35,
        tol=1e-8,
    )

    result = solve_bab_mlp(
        module,
        spec,
        config=config,
        query_recorder=recorder,
    )
    recorder.validate_complete()

    assert result.nodes_visited == len(recorder.entries)
    assert len(recorder.entries) >= 3
    assert recorder.entries[0].query.parent_query_id is None
    query_ids = [entry.query.query_id for entry in recorder.entries]
    assert len(query_ids) == len(set(query_ids))
    split_signatures = [entry.query.split_signature for entry in recorder.entries]
    assert split_signatures[0] == "root"
    assert len(split_signatures) == len(set(split_signatures))
    seen: set[str] = set()
    for entry in recorder.entries:
        assert (
            entry.query.parent_query_id is None or entry.query.parent_query_id in seen
        )
        seen.add(entry.query.query_id)
    assert all(
        entry.result is not None and entry.result.status in {"ok", "infeasible"}
        for entry in recorder.entries
    )

    comparisons = replay_fixed_query_trace(module, recorder.entries)
    assert len(comparisons) == len(recorder.entries)
    assert all(comparison.passed for comparison in comparisons)
    assert max(comparison.max_abs_diff for comparison in comparisons) <= 2e-4

    reversed_entries = list(reversed(recorder.entries))
    logical_batch = build_query_batch(
        [BoundQueryRequest(entry.query, entry.payload) for entry in reversed_entries],
        estimated_peak_bytes=0,
        memory_budget_bytes=1 << 30,
    )
    batch_results = execute_query_batch_reference(module, logical_batch)
    assert [query_id for query_id, _ in batch_results] == [
        entry.query.query_id for entry in reversed_entries
    ]
    for entry, (query_id, actual) in zip(reversed_entries, batch_results):
        assert entry.result is not None
        assert compare_query_results(query_id, entry.result, actual).passed

    physical_batch = build_query_batch(
        [BoundQueryRequest(entry.query, entry.payload) for entry in recorder.entries],
        estimated_peak_bytes=0,
        memory_budget_bytes=1 << 30,
    )
    physical_results = execute_alpha_beta_query_batch(module, physical_batch)
    assert [query_id for query_id, _ in physical_results] == query_ids
    for entry, (query_id, actual) in zip(recorder.entries, physical_results):
        assert entry.result is not None
        assert compare_query_results(query_id, entry.result, actual).passed
