#!/usr/bin/env bash
set -euo pipefail

# Installs paired Conda activation/deactivation hooks for the currently active env.
if [[ -z "${CONDA_PREFIX:-}" ]]; then
    echo "错误：没有活动的 Conda 环境。请先激活 boundflow，或通过 conda run 执行。" >&2
    exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SCRIPT="${PROJECT_ROOT}/env.sh"
ACTIVATE_DIR="${CONDA_PREFIX}/etc/conda/activate.d"
DEACTIVATE_DIR="${CONDA_PREFIX}/etc/conda/deactivate.d"
ACTIVATE_FILE="${ACTIVATE_DIR}/boundflow_activate.sh"
DEACTIVATE_FILE="${DEACTIVATE_DIR}/boundflow_deactivate.sh"

mkdir -p "${ACTIVATE_DIR}" "${DEACTIVATE_DIR}"

cat >"${ACTIVATE_FILE}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by boundflow/scripts/setup_hooks.sh.
for _boundflow_var in BOUNDFLOW_ROOT PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH TVM_FFI_DISABLE_TORCH_C_DLPACK TVM_FFI_CACHE_DIR TMPDIR; do
    if printenv "${_boundflow_var}" >/dev/null 2>&1; then
        export "_OLD_BOUNDFLOW_${_boundflow_var}=$(printenv "${_boundflow_var}")"
        export "_OLD_BOUNDFLOW_${_boundflow_var}_SET=1"
    else
        unset "_OLD_BOUNDFLOW_${_boundflow_var}" "_OLD_BOUNDFLOW_${_boundflow_var}_SET"
    fi
done
unset _boundflow_var
HOOK
printf 'source %q\n' "${ENV_SCRIPT}" >>"${ACTIVATE_FILE}"

cat >"${DEACTIVATE_FILE}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by boundflow/scripts/setup_hooks.sh.
for _boundflow_var in BOUNDFLOW_ROOT PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH TVM_FFI_DISABLE_TORCH_C_DLPACK TVM_FFI_CACHE_DIR TMPDIR; do
    _boundflow_old_var="_OLD_BOUNDFLOW_${_boundflow_var}"
    _boundflow_set_var="${_boundflow_old_var}_SET"
    if [[ "$(printenv "${_boundflow_set_var}")" == "1" ]]; then
        export "${_boundflow_var}=$(printenv "${_boundflow_old_var}")"
    else
        unset "${_boundflow_var}"
    fi
    unset "${_boundflow_old_var}" "${_boundflow_set_var}"
done
unset _boundflow_var _boundflow_old_var _boundflow_set_var
HOOK

chmod +x "${ACTIVATE_FILE}" "${DEACTIVATE_FILE}"
echo "Conda 钩子安装完成："
echo "  激活：${ACTIVATE_FILE}"
echo "  反激活：${DEACTIVATE_FILE}"
echo "重新执行 'conda activate boundflow' 后生效。"
