#!/bin/bash
# scripts/setup_hooks.sh
# Installs a Conda activation hook to source env.sh automatically.

if [ -z "$CONDA_PREFIX" ]; then
    echo "Error: No conda environment active. Please activate your target environment (e.g. 'conda activate boundflow') first."
    exit 1
fi

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
ENV_SCRIPT="$PROJECT_ROOT/env.sh"

ACTIVATE_DIR="$CONDA_PREFIX/etc/conda/activate.d"
DEACTIVATE_DIR="$CONDA_PREFIX/etc/conda/deactivate.d"

mkdir -p "$ACTIVATE_DIR"
mkdir -p "$DEACTIVATE_DIR"

ACTIVATE_FILE="$ACTIVATE_DIR/boundflow_activate.sh"
DEACTIVATE_FILE="$DEACTIVATE_DIR/boundflow_deactivate.sh"

# --- Generate Activation Script ---
echo "#!/bin/bash" > "$ACTIVATE_FILE"
echo "# Auto-generated by boundflow/scripts/setup_hooks.sh" >> "$ACTIVATE_FILE"
echo "# Save previous state" >> "$ACTIVATE_FILE"
echo "export _OLD_BOUNDFLOW_PYTHONPATH=\"\$PYTHONPATH\"" >> "$ACTIVATE_FILE"
echo "export _OLD_BOUNDFLOW_TVM_HOME=\"\$TVM_HOME\"" >> "$ACTIVATE_FILE"
echo "" >> "$ACTIVATE_FILE"
echo "# Source environment config" >> "$ACTIVATE_FILE"
echo "source \"$ENV_SCRIPT\"" >> "$ACTIVATE_FILE"

# --- Generate Deactivation Script ---
echo "#!/bin/bash" > "$DEACTIVATE_FILE"
echo "# Auto-generated by boundflow/scripts/setup_hooks.sh" >> "$DEACTIVATE_FILE"
echo "# Restore previous state" >> "$DEACTIVATE_FILE"
echo "" >> "$DEACTIVATE_FILE"
echo "if [ -n \"\$_OLD_BOUNDFLOW_PYTHONPATH\" ]; then" >> "$DEACTIVATE_FILE"
echo "    export PYTHONPATH=\"\$_OLD_BOUNDFLOW_PYTHONPATH\"" >> "$DEACTIVATE_FILE"
echo "else" >> "$DEACTIVATE_FILE"
echo "    unset PYTHONPATH" >> "$DEACTIVATE_FILE"
echo "fi" >> "$DEACTIVATE_FILE"
echo "" >> "$DEACTIVATE_FILE"
echo "if [ -n \"\$_OLD_BOUNDFLOW_TVM_HOME\" ]; then" >> "$DEACTIVATE_FILE"
echo "    export TVM_HOME=\"\$_OLD_BOUNDFLOW_TVM_HOME\"" >> "$DEACTIVATE_FILE"
echo "else" >> "$DEACTIVATE_FILE"
echo "    unset TVM_HOME" >> "$DEACTIVATE_FILE"
echo "fi" >> "$DEACTIVATE_FILE"
echo "" >> "$DEACTIVATE_FILE"
echo "unset _OLD_BOUNDFLOW_PYTHONPATH" >> "$DEACTIVATE_FILE"
echo "unset _OLD_BOUNDFLOW_TVM_HOME" >> "$DEACTIVATE_FILE"
echo "unset BOUNDFLOW_ROOT" >> "$DEACTIVATE_FILE"

# Make executable
chmod +x "$ACTIVATE_FILE"
chmod +x "$DEACTIVATE_FILE"

echo "Successfully configured Conda hooks:"
echo "  [Activate]   -> $ACTIVATE_FILE"
echo "  [Deactivate] -> $DEACTIVATE_FILE"
echo ""
echo "Changes will apply next time you run: conda activate boundflow"
